migrate:
	npx sequelize-cli db:migrate
migrate-undo:
	npx sequelize-cli db:migrate:undo
migrate-reset:
	npx sequelize-cli db:migrate:undo:all



seed-all:
	npx sequelize-cli db:seed:all
seed-undo:
	npx sequelize-cli db:seed:undo:all